### ISSUE TITLE
caching functions without arguments

### ISSUE THREAD

**Issue by bmc-msft** [lonelyenvoy/python-memoization#10]
Right now, [syntax warning](https://github.com/lonelyenvoy/python-memoization/blob/5bad6a56ff1f8df86c635bff95e51c832ff51185/memoization/memoization.py#L102) is generated with the following code.

```python
@cached
def expensive_function():
   ...
```

However, the use of `@cached` in this context can be useful in some contexts.  Example: `@cached` does effectively the same thing with significantly less code as the following construct using a global variable:

```python
HAS_RUN=False
def expensive_function():
   global HAS_RUN
   if HAS_RUN:
      return
   else:
      HAS_RUN=True
```

Can this syntax warning be configurable and/or removed?

**Comment by lonelyenvoy** [comment]
Resolved in v0.4.0. Now available at [PyPI](https://pypi.org/project/memoization/) or [GitHub Releases](https://github.com/lonelyenvoy/python-memoization/releases/tag/v0.4.0).

Please upgrade by: `pip install -U memoization`

The `SyntaxWarning` on functions without arguments has been removed.
