### ISSUE TITLE
[Q] Is there an ETA for Partial cache clearing ?

### ISSUE THREAD

**Issue by jakubczaplicki** [lonelyenvoy/python-memoization#14]
Is anyone actively working on this feature?

**Comment by lonelyenvoy** [comment]
Feature implemented in v0.4.0. Now available at [PyPI](https://pypi.org/project/memoization/) or [GitHub Releases](https://github.com/lonelyenvoy/python-memoization/releases/tag/v0.4.0).

Please upgrade by: `pip install -U memoization`

Use this API: [`cache_remove_if(predicate)`](https://github.com/lonelyenvoy/python-memoization#advanced-api-references)
