### ISSUE TITLE
remove particular element from cache?

### ISSUE THREAD

**Issue by rmrmg** [lonelyenvoy/python-memoization#19]
Hello I have function which can return results or timeout, simplified example is below:
```
@cache()
def longjob(args):
   try:
      data =  getdata(args)
      return data
  except timeout:
      return 'data not available try again later'
```
When  function cannot return data there is no reason to cache result. Is there any way to remove single entry from cache? I am aware of clear_cache() but this remove all cached values.

**Comment by lonelyenvoy** [comment]
Feature implemented in v0.4.0. Now available at [PyPI](https://pypi.org/project/memoization/) or [GitHub Releases](https://github.com/lonelyenvoy/python-memoization/releases/tag/v0.4.0).

Please upgrade by: `pip install -U memoization`

Use this API: [`cache_remove_if(predicate)`](https://github.com/lonelyenvoy/python-memoization#advanced-api-references)
